### ISSUE TITLE
detect some common errors from surface syntax

### ISSUE THREAD

**Issue by bobzhang** [rescript-lang/syntax#117]
from https://github.com/facebook/reason/issues/2626

```reason
@bs.val external someFunc : unit => (unit => unit) = "someFunc"
```
This is a common issue, what the user really wants is `type callback = unit -> unit .... unit -> callback`
thoughts?

**Comment by bobzhang** [comment]
@wlitwin This is a common pitfall of OCaml externals. Since OCaml is a curried language while C is an uncurried language, so the compiler will try to infer the arity of external functions based on surface syntax and do the uncurrin g under the hood.
However, the arity is inferred based on abstract syntax (instead of real concrete syntax) where `unit -> unit -> unit` is the same as `unit -> (unit -> unit)`, so the compiler will not infer the arity per user's thoughts

**Comment by wlitwin** [comment]
I think I'm still a bit confused. Why would it drop the extra application? Is there some kind of collapsing of unit parameters? And example 4 seems even weirder, because it chose the second curried parameter instead of the first. Does the compiler just take the last two (curried) arguments when generating the output?

```ocaml
Js.log("Attempt 4");
@bs.val external someFuncBool : unit => (bool => unit) = "someFunc"
someFuncBool()(true); // True is applied second here
```

```Javascript
console.log("Attempt 4");

someFunc(true); // Why is this using the true?
```

Thank you for taking the time to answer these questions!

**Comment by bobzhang** [comment]
@wlitwin the parser views the below two exactly the same, since `=>` is right associative
```reason
@bs.val external someFuncBool : unit => (bool => unit) = "someFunc"
@bs.val external someFuncBool : unit => bool => unit = "someFunc"
```
