### ISSUE TITLE
Issues around the \"Illegal Name" syntax

### ISSUE THREAD

**Issue by cannorin** [rescript-lang/syntax#149]
I've found several issues around the `\"Illegal Name"` syntax.

## Variants

The `\"Illegal Name"` syntax does not work for variant tags.

```reason
type \"Test Variant" =
  | \"Test Variant"
```

In this case, it produces the following error: ```Did you mean `Test Variant` instead of `Test Variant`?```.

Playground Link: https://rescript-lang.org/try?code=C4TwDgpgBAOgRAFQgZ2FAagQwE4EtMB2wcUAvAFBRQA+siKaWehx5QA

Only tags are affected since the following fails too:

```reason
type testVariant = | \"TestVariant"
```

Playground Link: https://rescript-lang.org/try?code=C4TwDgpgBMEM7AGoEMBOBLZA7YUC8UAPlADoBEAKvEmpjmUA

On the other hand, a variant with a legal tag name does not cause the problem.

```reason
type \"Test Variant" =
  | TestVariant
```

## Polymorphic variants

When `\"Illegal Name"` syntax is used with polymorphic variants, it produces an error: `File "env.ml", line 938, characters 26-32: Assertion failed`.

```reason
type \"Test Variant" = [ #\"Test Variant" ]
```

Playground Link: https://rescript-lang.org/try?code=C4TwDgpgBAOgRAFQgZ2FAagQwE4EtMB2wcUAvFANpQDE8SqGO+RJAukA

It also breaks with the same error even if the tag is legally named:

```reason
type \"Test Variant" = [ #TestVariant ]
```

Playground Link: https://rescript-lang.org/try?code=C4TwDgpgBAOgRAFQgZ2FAagQwE4EtMB2wcUAvFANpQDESqWehaAukA

However, the following compiles:

```reason
type testVariant = [ #\"Test Variant" ]
```

## Type Aliases

Type aliases also produce the same error: `File "env.ml", line 938, characters 26-32: Assertion failed`.

```reason
type \"Test Alias" = int
```

Playground Link: https://rescript-lang.org/try?code=C4TwDgpgBAOgRAFQgZ2FAggGwJYENlxQC8U2AdsEA

It also breaks with the same error when aliasing to an  `\"Illegal Name"` type:

```reason
type \"Test Variant" = | TestVariant

type testAlias = \"Test Variant"
```

Playground Link: https://rescript-lang.org/try?code=C4TwDgpgBAOgRAFQgZ2FAagQwE4EtMB2wcUAvFAD5RKpZ6HABQjokUwKwAggDb7JlYiThhz4icIA

**Comment by ryyppy** [comment]
First of all, the usage of `\""` syntax should be really exceptional and only be used for very specific cases.

Second, why would you want an illegal name for variant constructors / type names / type aliases? They are only used in the ReScript domain so it doesn't really make sense to bail out of the naming conventions.

The point of the "illegal name" syntax is to have better ways to interop with existing JS. E.g. `#"My Poly Variant` makes sense because poly vars can be compiled to plain strings (which is useful for string enums).

**Comment by cannorin** [comment]
Thanks for the response.

Let me explain the background: I'm writing a tool that generates ReScript wrappers from TypeScript definition files.

TypeScript has [Literal Types](https://www.typescriptlang.org/docs/handbook/literal-types.html) which is essentially a type-level string/number/boolean literal and I have to represent them in ReScript in some way.

I thought it would be better to use the `\""` syntax to represent those types (like `type \"hello"`) instead of generating not-very-human-readable type names (like `type literal_type_42`), and found those problems during trying it out.

I can definitely live with the current limitations (but it would be great if supported). I reported them just in case these are unintended behaviour.

**Comment by ryyppy** [comment]
> Let me explain the background: I'm writing a tool that generates ReScript wrappers from TypeScript definition files.

Thanks for the context. Please note that there have been a few project out there doing a similar thing already (e.g. [Reasonably Typed](https://github.com/rrdelaney/ReasonablyTyped) or [re-typescript](https://github.com/jsiebern/re-typescript)). Be aware that there are way more limitations than just naming conventions, since the type systems are very different and our language can't express many different and common TS constructs.

> TypeScript has Literal Types which is essentially type-level string/number/boolean literals and I have to represent them in ReScript in some way.

As far as I am aware, you can only represent string literal types with polymorphic variants here. `\""` works well for poly vars, so I don't see  a problem here.

> I thought it would be better to use the \"" syntax to represent those types (like type \"hello") instead of generating not-very-human-readable type names (like type literal_type_42), and found those problems during trying it out.

This might cause bad UX on the ReScript user side, because they'd need to write `\"my type name"` every time they want to use that type. Not sure if this is desirable?

**Comment by cannorin** [comment]
Thanks for letting me know jsiebern/re-typescript! I knew about rrdelaney/ReasonablyTyped but it seems not maintained anymore, so I decided to write one. I will take a look at jsiebern/re-typescript then.

> Be aware that there are way more limitations than just naming conventions, since the type systems are very different and our language can't express many different and common TS constructs.

I'm very aware of that :slightly_smiling_face: I have experiences in type systems so those are lesser issues for me.

> As far as I am aware, you can only represent string literal types with polymorphic variants here. \"" works well for poly vars, so I don't see a problem here.

Yes, I'm going to use poly variants for strings only.

> This might cause bad UX on the ReScript user side, because they'd need to write \"my type name" every time they want to use that type. Not sure if this is desirable?

Not sure either. I'm heavily biased in F#/Fable which represents string enums as the following:

```fsharp
    type [<StringEnum>] [<RequireQualifiedAccess>] IExportsSep =
        | [<CompiledName "\\">] ``\\``
        | [<CompiledName "/">] ``/``
```

If I do something like `type string_literal_42 = [ #\"hello, world!" ]` the users may have difficulty to lookup the type name for the type literal they want to use. Of course, I can make it a bit more readable as `type hello_world = ...` but then they might end up colliding each other if I don't choose a good way to "serialize" the string. 

On the other hand, if the following is given

```
module TypeLiterals = {
  type \"hello, world!" = [ #\"hello, world!" ]
}
```

the users may be able to pick up the type easily using the IDE's auto-completion feature. This is why I thought it is better.

**Comment by cannorin** [comment]
@ryyppy I also found out the `\""` syntax doesn't allow double quotations. There is a real-world example of using such string: https://github.com/microsoft/TypeScript/blob/master/lib/typescript.d.ts#L5466

I think this is an issue need to be fixed (unlike the ones above). Should I create a separate issue for this?

**Comment by IwanKaramazow** [comment]
The escaping mechanism is intended for special cases like keywords as lowercase identifiers. The variant definition will not work because it requires a uppercased (first character) identifier. This feature is too powerful, it is likely that we'll  restrict it in the future. Escape sequences are not implemented in the identifier escape mechanism. Using `type \"hello, world!"` is not advised and will likely be removed the future.

It's a bit unfortunate that TS represents everything as strings. We're dealing with two completely different type systems.

**Comment by jfrolich** [comment]
Perhaps it would make sense to remove the escaping feature and only implement it as annotations in very specific cases?

**Comment by cannorin** [comment]
@jfrolich That would be less confusing. Currently It looks much like that it could be used to any kind of identifier, so I expected that the codes above should work.
