### ISSUE TITLE
Conversion: JSX element is turned into a regular function call

### ISSUE THREAD

**Issue by bloodyowl** [rescript-lang/syntax#247]
In:

https://github.com/putaindecode/putaindecode.io/blob/747a76d404f17803c3892e24fb42dad0d19b2373/src/pages/ErrorPage.re

Out:

https://gist.github.com/bloodyowl/44f00cccdcd0b725873731bdc7d818af#file-errorpage-res-L125-L141

`bsb -version`: 8.3.3

**Comment by IwanKaramazow** [comment]
Hey,

This seems to have been fixed in https://github.com/rescript-lang/syntax/commit/db0c6b903eea21a4b18aab06f2469b0349bd5daa and has been released in newer bsb versions. Just tried the example of  `8.4.2` and it seems to work.
Can you try upgrading to the latest version? Any particular reason you haven't upgraded yet?

(Added another test case to rescript master to verify that it has been fixed in cf56dff20edd291ae4cde536ba007682a0fb934a).
