### ISSUE TITLE
reason to rescript conversion doesn't change "type t = [SomeModule.t]" to "type t = SomeModule.t"

### ISSUE THREAD

**Issue by ruifortes** [rescript-lang/syntax#253]
I guess it's a bug...

**Comment by bobzhang** [comment]
@ruifortes do you have some concrete examples?

**Comment by ruifortes** [comment]
This code from [bs-css-emotion](https://github.com/reasonml-labs/bs-css/blob/83ef30f6ea0ad66062cbe67fb404cb4d3ffa1500/bs-css/src/Css_AtomicTypes.re#L1667)

...it doesn't change this code:

``` reason
module CounterStyleType = {
  type t = [ ListStyleType.t];

  let toString =
    fun
    | #ListStyleType.t as c => ListStyleType.toString(c);
};
```
Guess it worked on reasonml but not on rescript.

**Comment by IwanKaramazow** [comment]
Thanks for the detailed example. I'm looking into this.

**Comment by IwanKaramazow** [comment]
@ruifortes thanks for the report! This is now fixed in master.

You can format code from `Reason` to `ReScript` in the playground: https://rescript-lang.org/try?ext=re&code=LYewJgrgNgpgBAYRBAdgFxgJwMpoJ6wAqeADvALxwDeAUHHPmQ3JQNpwAyAlgM5q4EYxMgDo0AXQDcNOnFhoGIXJi4oA5i1n0AZqi1wAPnADE3PgKKkYYuAEMecAMYsAfJ1798l0WiVoV6gAUjgCU0gC+0kA

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/10634678/106653100-a86abf80-6596-11eb-9202-946abc24daa6.png">

If you hit the `res` button in the settings, it will automatically convert your code to ReScript:
<img width="1358" alt="image" src="https://user-images.githubusercontent.com/10634678/106653185-c0dada00-6596-11eb-986d-868556311c6c.png">
