### ISSUE TITLE
Surprising formatting if boolean operators involved

### ISSUE THREAD

**Issue by jacobp100** [rescript-lang/syntax#321]
The following code is formatted,

```res
let isNaN = (a: t) =>
  switch a {
  | #Z => false
  | #R(v)
  | #I(v) =>
    Real.isNaN(v)
  | #C(re, im) => Real.isNaN(re) || Real.isNaN(im)
  }
```

It's strange that on the `#I` case it breaks onto a line, but the line below is not.

**Comment by johnridesabike** [comment]
I believe this is because there's a linebreak between `| #R(v)` and `| #I(v)`. If you write both of the conditions on one line, then the formatter preserves all one one line. But if you add a linebreak between them, then it adds another linebreak after the `=>` too.

```res
let isNaN = (a: t) =>
  switch a {
  | #Z => false
  | #R(v) | #I(v) => Real.isNaN(v)
  | #C(re, im) => Real.isNaN(re) || Real.isNaN(im)
  }
```
[Clicking "format" does not change this code.](https://rescript-lang.org/try?code=DYUwLgBAlgzgcgQzhAvBAFAgXBMBKVAPgCgIIYB3KMAYwAsIEIBvUiAHwgGIAtIiAGYJgMEG05cASugBuBCQElZBFIQiSQwgHSxEcZeO4BhdACcQAGmgBbFWo3bdSMyHmcHwHfGdRbbAL7EQA)

**Comment by jacobp100** [comment]
Good to know! Thanks!
