### ISSUE TITLE
Variant constructor `X` can't be found, despite module being in scope

### ISSUE THREAD

**Issue by lessp** [rescript-lang/syntax#342]
The following code:

```reason
module A = {
  type foo = X | Y

  type t = {
    ch: char,
    f: foo,
  }
}

module B = {
  type t = Foo | Bar(A.t)
}

let foo: string => B.t = text => {
  let currentCharcter = text->String.unsafe_get(0)

  let x = switch currentCharcter {
  | 'a' .. 'z' as letter => Bar({ch: letter, f: X})
  }
  x
}
```

Generates the following error:

![image](https://user-images.githubusercontent.com/17602389/112381092-dba61100-8cf2-11eb-8cfa-fccf1d75bfb5.png)

However. If I don't assign the result to `x`, like this:

```reason
module A = {
  type foo = X | Y

  type t = {
    ch: char,
    f: foo,
  }
}

module B = {
  type t = Foo | Bar(A.t)
}

let foo: string => B.t = text => {
  let currentCharcter = text->String.unsafe_get(0)

  // NOTE: See here
  switch currentCharcter {
  | 'a' .. 'z' as letter => Bar({ch: letter, f: X})
  }
}
```

Code works as expected.

**Comment by gaku-sei** [comment]
I may be wrong here but the explanation could come from the way the OCaml type checker goes from top to bottom (sorry I don't have any link to share here).

What it means is that in the second example the returned value (the switch) is explicitely `B.t` (it's part of `foo`'s definition) so OCaml/ReScript can easily assume `Bar` is a value that belongs to `B.t`.

In the first example, when assigning to `x` the compiler doesn't know _yet_ what x's type is supposed to be, and therefore what `Bar` is, and since type checking is done in one pass only, it'll stop checking the code here. That's what i mean by top to bottom.

Notice that in most cases it's not an issue and you should probably name all values that are not in the exact same module. Bear in mind the compiler is never wrong and you can remove the type annotation of `foo` and use `B.Bar` explicitely instead, the code will always compile, with or without the intermediate `x` variable and the function `foo`'s type will be infered properly by the compiler and be displayed on mouse over by the rescript IDE extension 🙂

**Comment by bobzhang** [comment]
This works as expected. Note Bar is not in scope, it is hidden in a submodule. Why your another piece of code works is because the result is annotated with type B.t.

```
let u : B.t = Bar(xx) // works, best practice
let u = B.Bar(xx) // also works
```
