### ISSUE TITLE
Infix operator support 

### ISSUE THREAD

**Issue by IwanKaramazow** [rescript-lang/syntax#440]
Implement parsing of operator tokens for value bindings and value description without escaping.

**Comment by snatvb** [comment]
Could you explain? I think that I will be able to write own operator -- `:+:` for example.

**Comment by digitake** [comment]
We need this. It's essential for a language to be used as DSL. That's one of the major reasons.

**Comment by chrischen** [comment]
Use cases like >=> can be replaced with function calls to flatMap or bind, but I can't find a good looking workaround for doing stuff like...

Where <$> is a map function and <*> is apply.
```
someFunc <$> param1 <*> param2
```

Have to be rewritten like this.
```
apply(map(someFunc, param1), param2)
```

**Comment by chrischen** [comment]
I would also like to add that this is a standard thing supported in F#, Haskell, Reason., Ocaml, and many other functional languages, so it’s not just some esoteric domain specific use of infixes.

Since the -> syntax works almost the same was as an infix (and can be defined as an infix) I don’t think it’s that much of a mental leap for newcomers to learn and parse infixes. Plus they’d be learning well established paradigms.

Thanks!
Chris
Creative Consultant
________________________________

**Comment by TheSpyder** [comment]
yes, because ReScript doesn't have infix they can't be defined _or_  used. The translation to use those functions right now is `\">>="(d6, num => Distrib.pure(num < 4))`.



> Note: Infix `>>=` wouldn't help here either. I'd love to have `let*` syntax. But as far as I can tell even the OCaml compiler coming with rescript doesn't have it

Indeed. It's based on 4.06, `let*` was added in 4.08.
